### ISSUE TITLE
ntpdate plugin misparses report for some NTP servers

### ISSUE THREAD

**Issue by glyndon** [munin-monitoring/muninlite#16]
NTPdate plugin with server set to pool.ntp.org results in a parsing failure for the 'delay' value.
Failure occurs only for 'ntpdate' reports containing multiple 'server' lines (such as when used with a pool of servers).

Has been this way for at least a year, on multiple machines, all running OpenWrt (usually kept at the latest stable version, currently 21.02.3)

It may have something to do with the rotating DNS resolution of that pool, or the number of servers returned by the 'ntpdate' binary
I don't know awk, so can't be sure if the issue is there.

A workaround so far is to insert ' | grep ^server | head -n1 ' Just before the call to awk.

**Comment by sumpfralle** [comment]
Thank you for your report and your proposal for fixing the issue.

I fixed this now in a similar way by stopping awk after it processed the first valid line of input.
