### ISSUE TITLE
df config vs fetch

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/muninlite#5]
OpenWRT:

<pre>
root@naru:~# df -PT
Filesystem           Type       1024-blocks    Used Available Capacity Mounted on
/dev/root            squashfs        3840      3840         0 100% /rom
tmpfs                tmpfs         240228      1140    239088   0% /tmp
/dev/loop0           ext4           55765      5103     46335  10% /overlay
overlayfs:/overlay   overlay        55765      5103     46335  10% /
tmpfs                tmpfs            512         0       512   0% /dev

root@naru:~# ./muninlite 
# munin node at naru.bbbs.net
config df
graph_title Filesystem usage (in %)
graph_args --upper-limit 100 -l 0
graph_vlabel %
graph_category disk
graph_info This graph shows disk usage on the machine.
_dev_loop0.label /overlay
_dev_loop0.info _dev_loop0 -> /overlay
_dev_loop0.warning 92
_dev_loop0.critical 98
.
fetch df
_dev_root.value 100
_dev_loop0.value 10
.
</pre>

Config uses IGNORE_FILESYSTEM_REGEX to skip "_dev_root", fetch doesn't. It should.

**Comment by sumpfralle** [comment]
Fixed by @kimheino in 5206847aa10b8a2f9a41782e0990eaca9203f658.

Thanks!
